# Generated by Django 2.2.6 on 2019-12-05 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '__first__'),
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambiente.Ambiente'),
        ),
    ]
